dist: bionic
sudo: required
matrix:
  include:
    - os: linux
    - os: osx
language: c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-multilib; fi
script:
  - ./build.sh
  - ./build.sh -p "x86" -l